-- MySQL Script generated by MySQL Workbench
-- Sun Dec  3 14:39:39 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema IeetBanco2.3
-- -----------------------------------------------------
-- By Paulo Henry tentativa 2
-- 
-- -----------------------------------------------------
-- Schema ieetbanco
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ieetbanco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ieetbanco` DEFAULT CHARACTER SET utf8 ;
USE `ieetbanco` ;
drop database `ieetbanco`;
-- -----------------------------------------------------
-- Table `ieetbanco`.`ieet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ieetbanco`.`ieet` (
  `idUsuarioAdmin` INT(11) NOT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `login` VARCHAR(45) NULL DEFAULT NULL,
  `senha` VARCHAR(100) NULL DEFAULT NULL,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idUsuarioAdmin`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ieetbanco`.`usuario_direcao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ieetbanco`.`usuario_direcao` (
  `idUsuarioDirecao` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `login` VARCHAR(45) NULL DEFAULT NULL,
  `senha` VARCHAR(100) NULL DEFAULT NULL,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  `Ieet_idUsuarioAdmin` INT(11) NOT NULL,
  PRIMARY KEY (`idUsuarioDirecao`),
  INDEX `fk_Usuario_Direcao_Ieet1_idx` (`Ieet_idUsuarioAdmin` ASC),
  CONSTRAINT `fk_Usuario_Direcao_Ieet1`
    FOREIGN KEY (`Ieet_idUsuarioAdmin`)
    REFERENCES `ieetbanco`.`ieet` (`idUsuarioAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ieetbanco`.`escola`
-- -----------------------------------------------------
drop table `ieetbanco`.`escola`;

CREATE TABLE IF NOT EXISTS `ieetbanco`.`escola` (
  `idEscola` INT(11) NOT NULL auto_increment,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `cnpj` VARCHAR(45) NULL DEFAULT NULL,
  `Usuario_Direcao_idUsuarioDirecao` INT(11) NOT NULL,
  PRIMARY KEY (`idEscola`),
  INDEX `fk_Escola_Usuario_Direcao1_idx` (`Usuario_Direcao_idUsuarioDirecao` ASC),
  CONSTRAINT `fk_Escola_Usuario_Direcao1`
    FOREIGN KEY (`Usuario_Direcao_idUsuarioDirecao`)
    REFERENCES `ieetbanco`.`usuario_direcao` (`idUsuarioDirecao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ieetbanco`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ieetbanco`.`turma` (
  `idTurma` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `Escola_idEscola` INT(11) NOT NULL,
  PRIMARY KEY (`idTurma`),
  INDEX `fk_Turma_Escola1_idx` (`Escola_idEscola` ASC),
  CONSTRAINT `fk_Turma_Escola1`
    FOREIGN KEY (`Escola_idEscola`)
    REFERENCES `ieetbanco`.`escola` (`idEscola`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ieetbanco`.`disciplinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ieetbanco`.`disciplinas` (
  `idDisciplinas` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `Turma_idTurma` INT(11) NOT NULL,
  `carga_Horaria` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idDisciplinas`),
  INDEX `fk_Disciplinas_Turma1_idx` (`Turma_idTurma` ASC),
  CONSTRAINT `fk_Disciplinas_Turma1`
    FOREIGN KEY (`Turma_idTurma`)
    REFERENCES `ieetbanco`.`turma` (`idTurma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ieetbanco`.`atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ieetbanco`.`atividade` (
  `idAtividade` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NULL DEFAULT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `dataFinal` DATE NULL DEFAULT NULL,
  `dataInicial` DATE NULL DEFAULT NULL,
  `Disciplinas_idDisciplinas` INT(11) NOT NULL,
  PRIMARY KEY (`idAtividade`),
  INDEX `fk_Atividade_Disciplinas_idx` (`Disciplinas_idDisciplinas` ASC),
  CONSTRAINT `fk_Atividade_Disciplinas`
    FOREIGN KEY (`Disciplinas_idDisciplinas`)
    REFERENCES `ieetbanco`.`disciplinas` (`idDisciplinas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ieetbanco`.`usuario_aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ieetbanco`.`usuario_aluno` (
  `idUsuarioAluno` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `cpf` VARCHAR(45) NULL DEFAULT NULL,
  `login` VARCHAR(45) NULL DEFAULT NULL,
  `senha` VARCHAR(100) NULL DEFAULT NULL,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  `dataDeNascimento` DATE NULL DEFAULT NULL,
  `dataDeCriacao` DATE NULL DEFAULT NULL,
  `Turma_idTurma` INT(11) NOT NULL,
  `matricula` VARCHAR(45) NULL DEFAULT NULL,
  `Escola_idEscola` INT(11) NOT NULL,
  PRIMARY KEY (`idUsuarioAluno`),
  INDEX `fk_Usuario_aluno_Turma1_idx` (`Turma_idTurma` ASC),
  INDEX `fk_Usuario_aluno_Escola1_idx` (`Escola_idEscola` ASC),
  CONSTRAINT `fk_Usuario_aluno_Escola1`
    FOREIGN KEY (`Escola_idEscola`)
    REFERENCES `ieetbanco`.`escola` (`idEscola`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_aluno_Turma1`
    FOREIGN KEY (`Turma_idTurma`)
    REFERENCES `ieetbanco`.`turma` (`idTurma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ieetbanco`.`notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ieetbanco`.`notas` (
  `idNotas` INT(11) NOT NULL AUTO_INCREMENT,
  `nota1.1` FLOAT NULL DEFAULT NULL,
  `nota1.2` FLOAT NULL DEFAULT NULL,
  `nota1.3` FLOAT NULL DEFAULT NULL,
  `nota2.1` FLOAT NULL DEFAULT NULL,
  `nota2.2` FLOAT NULL DEFAULT NULL,
  `nota2.3` FLOAT NULL DEFAULT NULL,
  `nota3.1` FLOAT NULL DEFAULT NULL,
  `nota3.2` FLOAT NULL DEFAULT NULL,
  `nota3.3` FLOAT NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT NULL,
  `Disciplinas_idDisciplinas` INT(11) NOT NULL,
  `Usuario_aluno_idUsuario` INT(11) NOT NULL,
  PRIMARY KEY (`idNotas`),
  INDEX `fk_Notas_Disciplinas1_idx` (`Disciplinas_idDisciplinas` ASC),
  INDEX `fk_Notas_Usuario_aluno1_idx` (`Usuario_aluno_idUsuario` ASC),
  CONSTRAINT `fk_Notas_Disciplinas1`
    FOREIGN KEY (`Disciplinas_idDisciplinas`)
    REFERENCES `ieetbanco`.`disciplinas` (`idDisciplinas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Notas_Usuario_aluno1`
    FOREIGN KEY (`Usuario_aluno_idUsuario`)
    REFERENCES `ieetbanco`.`usuario_aluno` (`idUsuarioAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ieetbanco`.`usuario_professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ieetbanco`.`usuario_professor` (
  `idUsuarioProfessor` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `cpf` VARCHAR(45) NULL DEFAULT NULL,
  `login` VARCHAR(45) NULL DEFAULT NULL,
  `senha` VARCHAR(100) NULL DEFAULT NULL,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  `dataDeNascimento` DATE NULL DEFAULT NULL,
  `dataDeCriacao` DATE NULL DEFAULT NULL,
  `Disciplinas_idDisciplinas` INT(11) NOT NULL,
  `matricula` VARCHAR(45) NULL DEFAULT NULL,
  `Escola_idEscola` INT(11) NOT NULL,
  `formacao` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuarioProfessor`),
  INDEX `fk_Usuario_Professor_Disciplinas1_idx` (`Disciplinas_idDisciplinas` ASC),
  INDEX `fk_Usuario_Professor_Escola1_idx` (`Escola_idEscola` ASC),
  CONSTRAINT `fk_Usuario_Professor_Disciplinas1`
    FOREIGN KEY (`Disciplinas_idDisciplinas`)
    REFERENCES `ieetbanco`.`disciplinas` (`idDisciplinas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Professor_Escola1`
    FOREIGN KEY (`Escola_idEscola`)
    REFERENCES `ieetbanco`.`escola` (`idEscola`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
