-- MySQL Script generated by MySQL Workbench
-- Sat Dec  2 16:28:43 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema IeetBanco
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema IeetBanco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `IeetBanco` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema ieet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ieet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ieet` DEFAULT CHARACTER SET utf8mb4 ;
USE `IeetBanco` ;

-- -----------------------------------------------------
-- Table `IeetBanco`.`Disciplinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IeetBanco`.`Disciplinas` (
  `idDisciplinas` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `Turma_idTurma` INT NOT NULL,
  `carga_Horaria` VARCHAR(45) NULL,
  PRIMARY KEY (`idDisciplinas`),
  INDEX `fk_Disciplinas_Turma1_idx` (`Turma_idTurma` ASC),
  CONSTRAINT `fk_Disciplinas_Turma1`
    FOREIGN KEY (`Turma_idTurma`)
    REFERENCES `IeetBanco`.`Turma` (`idTurma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IeetBanco`.`Ieet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IeetBanco`.`Ieet` (
  `idUsuarioAdmin` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `login` VARCHAR(45) NULL,
  `senha` VARCHAR(100) NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuarioAdmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IeetBanco`.`Usuario_Direcao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IeetBanco`.`Usuario_Direcao` (
  `idUsuarioDirecao` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `login` VARCHAR(45) NULL,
  `senha` VARCHAR(100) NULL,
  `tipo` VARCHAR(45) NULL,
  `Ieet_idUsuarioAdmin` INT NOT NULL,
  PRIMARY KEY (`idUsuarioDirecao`),
  INDEX `fk_Usuario_Direcao_Ieet1_idx` (`Ieet_idUsuarioAdmin` ASC),
  CONSTRAINT `fk_Usuario_Direcao_Ieet1`
    FOREIGN KEY (`Ieet_idUsuarioAdmin`)
    REFERENCES `IeetBanco`.`Ieet` (`idUsuarioAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IeetBanco`.`Escola`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IeetBanco`.`Escola` (
  `idEscola` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `cnpj` VARCHAR(45) NULL,
  `Usuario_Direcao_idUsuarioDirecao` INT NOT NULL,
  PRIMARY KEY (`idEscola`),
  INDEX `fk_Escola_Usuario_Direcao1_idx` (`Usuario_Direcao_idUsuarioDirecao` ASC),
  CONSTRAINT `fk_Escola_Usuario_Direcao1`
    FOREIGN KEY (`Usuario_Direcao_idUsuarioDirecao`)
    REFERENCES `IeetBanco`.`Usuario_Direcao` (`idUsuarioDirecao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IeetBanco`.`Usuario_Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IeetBanco`.`Usuario_Professor` (
  `idUsuarioProfessor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `cpf` VARCHAR(45) NULL,
  `login` VARCHAR(45) NULL,
  `senha` VARCHAR(100) NULL,
  `tipo` VARCHAR(45) NULL,
  `dataDeNascimento` DATE NULL,
  `dataDeCriacao` DATE NULL,
  `Disciplinas_idDisciplinas` INT NOT NULL,
  `matricula` VARCHAR(45) NULL,
  `Escola_idEscola` INT NOT NULL,
  PRIMARY KEY (`idUsuarioProfessor`),
  INDEX `fk_Usuario_Professor_Disciplinas1_idx` (`Disciplinas_idDisciplinas` ASC),
  INDEX `fk_Usuario_Professor_Escola1_idx` (`Escola_idEscola` ASC),
  CONSTRAINT `fk_Usuario_Professor_Disciplinas1`
    FOREIGN KEY (`Disciplinas_idDisciplinas`)
    REFERENCES `IeetBanco`.`Disciplinas` (`idDisciplinas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Professor_Escola1`
    FOREIGN KEY (`Escola_idEscola`)
    REFERENCES `IeetBanco`.`Escola` (`idEscola`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IeetBanco`.`Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IeetBanco`.`Turma` (
  `idTurma` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `Usuario_Professor_idUsuario` INT NOT NULL,
  `Escola_idEscola` INT NOT NULL,
  PRIMARY KEY (`idTurma`),
  INDEX `fk_Turma_Usuario_Professor1_idx` (`Usuario_Professor_idUsuario` ASC),
  INDEX `fk_Turma_Escola1_idx` (`Escola_idEscola` ASC),
  CONSTRAINT `fk_Turma_Usuario_Professor1`
    FOREIGN KEY (`Usuario_Professor_idUsuario`)
    REFERENCES `IeetBanco`.`Usuario_Professor` (`idUsuarioProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turma_Escola1`
    FOREIGN KEY (`Escola_idEscola`)
    REFERENCES `IeetBanco`.`Escola` (`idEscola`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IeetBanco`.`Atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IeetBanco`.`Atividade` (
  `idAtividade` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NULL,
  `descricao` TEXT NULL,
  `dataFinal` DATE NULL,
  `dataInicial` DATE NULL,
  `Disciplinas_idDisciplinas` INT NOT NULL,
  PRIMARY KEY (`idAtividade`),
  INDEX `fk_Atividade_Disciplinas_idx` (`Disciplinas_idDisciplinas` ASC),
  CONSTRAINT `fk_Atividade_Disciplinas`
    FOREIGN KEY (`Disciplinas_idDisciplinas`)
    REFERENCES `IeetBanco`.`Disciplinas` (`idDisciplinas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IeetBanco`.`Usuario_aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IeetBanco`.`Usuario_aluno` (
  `idUsuarioAluno` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `cpf` VARCHAR(45) NULL,
  `login` VARCHAR(45) NULL,
  `senha` VARCHAR(100) NULL,
  `tipo` VARCHAR(45) NULL,
  `dataDeNascimento` DATE NULL,
  `dataDeCriacao` DATE NULL,
  `Turma_idTurma` INT NOT NULL,
  `matricula` VARCHAR(45) NULL,
  `Escola_idEscola` INT NOT NULL,
  PRIMARY KEY (`idUsuarioAluno`),
  INDEX `fk_Usuario_aluno_Turma1_idx` (`Turma_idTurma` ASC),
  INDEX `fk_Usuario_aluno_Escola1_idx` (`Escola_idEscola` ASC),
  CONSTRAINT `fk_Usuario_aluno_Turma1`
    FOREIGN KEY (`Turma_idTurma`)
    REFERENCES `IeetBanco`.`Turma` (`idTurma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_aluno_Escola1`
    FOREIGN KEY (`Escola_idEscola`)
    REFERENCES `IeetBanco`.`Escola` (`idEscola`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IeetBanco`.`Notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IeetBanco`.`Notas` (
  `idNotas` INT NOT NULL AUTO_INCREMENT,
  `nota1.1` FLOAT NULL,
  `nota1.2` FLOAT NULL,
  `nota1.3` FLOAT NULL,
  `nota2.1` FLOAT NULL,
  `nota2.2` FLOAT NULL,
  `nota2.3` FLOAT NULL,
  `nota3.1` FLOAT NULL,
  `nota3.2` FLOAT NULL,
  `nota3.3` FLOAT NULL,
  `status` INT NULL,
  `Disciplinas_idDisciplinas` INT NOT NULL,
  `Usuario_aluno_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idNotas`),
  INDEX `fk_Notas_Disciplinas1_idx` (`Disciplinas_idDisciplinas` ASC),
  INDEX `fk_Notas_Usuario_aluno1_idx` (`Usuario_aluno_idUsuario` ASC),
  CONSTRAINT `fk_Notas_Disciplinas1`
    FOREIGN KEY (`Disciplinas_idDisciplinas`)
    REFERENCES `IeetBanco`.`Disciplinas` (`idDisciplinas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Notas_Usuario_aluno1`
    FOREIGN KEY (`Usuario_aluno_idUsuario`)
    REFERENCES `IeetBanco`.`Usuario_aluno` (`idUsuarioAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `ieet` ;

-- -----------------------------------------------------
-- Table `ieet`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ieet`.`usuarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `data_nasc` DATE NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `tipo` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ieet`.`alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ieet`.`alunos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_usuario` (`id_usuario` ASC),
  CONSTRAINT `alunos_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `ieet`.`usuarios` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ieet`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ieet`.`professor` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_id` INT(11) NULL DEFAULT NULL,
  `total_ch` INT(11) NULL DEFAULT NULL,
  `disciplina` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `usuario_id` (`usuario_id` ASC),
  CONSTRAINT `professor_ibfk_1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `ieet`.`usuarios` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ieet`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ieet`.`turma` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `aluno_id` INT(11) NULL DEFAULT NULL,
  `professor_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `aluno_id` (`aluno_id` ASC),
  INDEX `professor_id` (`professor_id` ASC),
  CONSTRAINT `turma_ibfk_1`
    FOREIGN KEY (`aluno_id`)
    REFERENCES `ieet`.`alunos` (`id`),
  CONSTRAINT `turma_ibfk_2`
    FOREIGN KEY (`professor_id`)
    REFERENCES `ieet`.`professor` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ieet`.`disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ieet`.`disciplina` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `turma_id` INT(11) NULL DEFAULT NULL,
  `professor_id` INT(11) NULL DEFAULT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `ch_total` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `turma_id` (`turma_id` ASC),
  INDEX `professor_id` (`professor_id` ASC),
  CONSTRAINT `disciplina_ibfk_1`
    FOREIGN KEY (`turma_id`)
    REFERENCES `ieet`.`turma` (`id`),
  CONSTRAINT `disciplina_ibfk_2`
    FOREIGN KEY (`professor_id`)
    REFERENCES `ieet`.`professor` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ieet`.`notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ieet`.`notas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_aluno` INT(11) NULL DEFAULT NULL,
  `nota1` FLOAT NULL DEFAULT NULL,
  `nota2` FLOAT NULL DEFAULT NULL,
  `nota3` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_aluno` (`id_aluno` ASC),
  CONSTRAINT `notas_ibfk_1`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `ieet`.`alunos` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
