CREATE DATABASE teste;
USE teste;

CREATE TABLE IF NOT EXISTS usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
	data_nasc DATE NOT NULL,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    tipo INT NOT NULL
);

CREATE TABLE IF NOT EXISTS notas(
	id INT AUTO_INCREMENT PRIMARY KEY,
    id_aluno INT,
    nota1 FLOAT,
    nota2 FLOAT,
    nota3 FLOAT,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);